name: Builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout/@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.1'
        check-latest: false
    - name: Builds
      run: |
        cd lib/impl && cargo build --release --verbose && cd ../..
        go build -v ./...

