name: CI

on:
  pull_request:
    push:
      branches: [ main ]

jobs:
  check:
    name: Cargo check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        rust: [ stable, nightly ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchainr: ${{ matrix.rust }}
          override: true
      - name: Cargo check
        run: make check-rust

  format:
    name: Cargo format
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        rust: [ stable ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchainr: ${{ matrix.rust }}
          override: true
      - run: rustup component add rustfmt
      - name: Cargo format
        run: make format-rust

  clippy:
    name: Clippy lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        rust: [ stable ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchainr: ${{ matrix.rust }}
          override: true
      - name: Change directory
        run: cd ./alloy.rs/
      - name: Clippy lint
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-review'
          clippy_flags: --all-features
