name: Go build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout/@v3
    - name: Build
      with:
      go-version: '>=1.19.1'
      run: go version
      run: go build -v ./...

