name: Go tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout/@v3
    - name: Tests
      with:
      go-version: '>=1.19.1'
      run: go test -v ./...

