name: Go tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.1'
        check-latest: false
    - name: Tests    
      run: go build ./... && go test -v ./...

