name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    brainces: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout/@v2
    - name: Build
      run: cd lib/impl && cargo build --release --verbose
    - name: Tests
      run: cd lib/impl && cargo test --verbose

